#pretraining with SimSiam
pretraining:
  batch_size: 10
  learning_rate: 0.0016612
  epochs: 2
  gpus: 0
  out_dim: 512
  pred_hidden_dim: 128
  proj_hidden_dim: 512
  num_ftrs: 512
  #input size of image
  input_size: 256

finetuning:
  batch_size: 256
  learning_rate: 0.0016612
  epochs: 2

UNet:
  # define the number of channels in the input, number of classes,
  channels: 1
  num_classes: 1
  dropout: 0.3












